kind: Service
apiVersion: v1
metadata:
  name: $ApplicationName
  labels:
    app.kubernetes.io/name: $ApplicationName
    app.kubernetes.io/part-of: $ApplicationNamespace
spec:
  selector:
    app.kubernetes.io/name: $ApplicationName
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
