global using FastEndpoints;
global using FluentValidation;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.DependencyInjection;
global using Oakton;
global using OneOf;
global using Scalar.AspNetCore;
global using System.Net;
global using System.Reflection;
// Solution usings
global using TimeWarp.Architecture.CorsPolicies;
global using TimeWarp.Architecture.Types;
global using TimeWarp.Mediator;
global using TimeWarp.Mediator.Pipeline;
