#region Purpose
// Generates FastEndpoint classes from [ApiEndpoint] contract types in referenced assemblies.
#endregion

#region Design
// Opt-in via the EnableApiEndpointGeneration MSBuild property (default false) so any project can
// reference the analyzers package without silently emitting endpoints.
// Scans referenced-assembly symbols rather than the current compilation's syntax: contracts live
// in a separate project from the server that hosts the generated endpoints.
// Host discovery walks only refs stamped [assembly: ApiEndpointsEmbedded] — MSBuild passes the
// transitive closure, so without the marker every framework namespace tree would be walked.
// Product contracts apply the public attributes-package marker; this generator also stamps an
// internal copy when the current compilation declares [ApiEndpoint] (test harness).
// ApiEndpointContractAssemblies (semicolon-separated AssemblyName values, e.g. web-contracts) is
// required when generation is enabled: it is an allow-list, not a docs namespace. Empty, typo, or
// unmarked names report TWE008 (Error) and emit nothing — TWA0019-style fail-closed.
// Equatable GenerationOptions + content-equal EndpointEmitModel so .Collect() does not rebuild
// every *Endpoint.g.cs on unrelated host edits.
// Reports SG002 once per batch when FastEndpoints/BaseFastEndpoint are absent — feature flags
// can strip those references while the generator package remains attached.
// Catches all exceptions (CA1031): a throwing generator would break the entire compilation.
// Request type is Query or Command per metadata.RequestTypeName; HTTP verb comes from resolved
// enum member name (not the underlying int). Fail-closed verbs (F-008 / TWE007): never default
// an unknown verb to Get — report and skip that contract.
// Missing nested Query/Command → TWE002, no emission.
// Auth (task 110, fail-closed default):
// [EndpointAuthorize] → Policies/Roles/AuthSchemes; [EndpointAllowAnonymous] → AllowAnonymous();
// NEITHER attribute → emit nothing (FastEndpoints requires authentication by default).
// Empty request DTOs (no public properties) get EmptyRequestBinder — FE's default binder rejects them.
// Summary/Description only — no weather-specific ExampleRequest.
// OpenAPI feature grouping: FE Tags() is endpoint-filter metadata only (no relationship with
// OpenAPI tags — see FastEndpoints configuration docs). Scalar sidebar groups by OpenAPI
// operation tags, so emission pairs Tags(...) with Description(d => d.WithTags(...)).
// Leaf feature Id comes from EndpointEmitModel (…Features.Admin.Roles → "Roles").
// F-003: per-compilation route conflict via equatable models + .Collect() + in-batch group-by
// (Route, HttpVerb). TWE003 on ALL parties; generate NONE of a conflict group. No static
// ConcurrentDictionary / RouteRegistry — IDE incremental and multi-project compiler-server
// runs cannot self-conflict or cross-pollute.
// F-004: discovery via HostedRouteDiscovery (linked shared source); [ClientOnlyContract] on
// outer or nested skips generation (TWA0020 flags the contradiction in convention analyzers).
// F-005: base type is always BaseFastEndpoint (EndpointType override deleted).
#endregion

namespace TimeWarp.Architecture.Analyzers;

using System.Collections.Generic;
using TimeWarp.Architecture.Analyzers.Models;

/// <summary>Source generator that emits FastEndpoint HTTP shims for [ApiEndpoint] contracts.</summary>
[Generator]
public class FastEndpointSourceGenerator : IIncrementalGenerator
{
  // Generator is disabled by default.
  // Consumers must explicitly set <EnableApiEndpointGeneration>true</EnableApiEndpointGeneration>
  // (or via their feature flag system) in their .csproj / Directory.Build.props.

  private const string MarkerAttributeSource =
    """
    // <auto-generated/>
    #nullable enable
    namespace TimeWarp.Architecture;

    [System.AttributeUsage(System.AttributeTargets.Assembly, Inherited = false)]
    internal sealed class ApiEndpointsEmbeddedAttribute : System.Attribute
    {
    }
    """;

  private const string MarkerSource =
    """
    // <auto-generated/>
    [assembly: TimeWarp.Architecture.ApiEndpointsEmbedded]
    """;

  /// <summary>Registers incremental generator steps for FastEndpoint emission.</summary>
  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    IncrementalValueProvider<bool> stampMarker =
      context.CompilationProvider.Select(
        static (compilation, _) => HostedRouteDiscovery.CompilationDeclaresApiEndpoint(compilation));

    context.RegisterSourceOutput(stampMarker, static (spc, shouldStamp) =>
    {
      if (!shouldStamp)
      {
        return;
      }

      // Attribute type + assembly stamp together (unlike TypedId post-init of the attribute
      // class on every compilation). Servers that only consume marked refs must not grow an
      // extra generated file on every host edit.
      spc.AddSource("ApiEndpointsEmbeddedAttribute.g.cs", SourceText.From(MarkerAttributeSource, Encoding.UTF8));
      spc.AddSource("ApiEndpointsEmbedded.g.cs", SourceText.From(MarkerSource, Encoding.UTF8));
    });

    // MSBuild properties controlling generation. Default Enable=false (opt-in).
    // ApiEndpointContractAssemblies is required when enabled (AssemblyName allow-list).
    IncrementalValueProvider<GenerationOptions> generationOptions =
      context.AnalyzerConfigOptionsProvider.Select(
        static (options, _) => GenerationOptions.Read(options.GlobalOptions));

    IncrementalValueProvider<ImmutableArray<string>> missingContractAssemblies =
      context.CompilationProvider
        .Combine(generationOptions)
        .Select(static (tuple, _) => FindMissingContractAssemblies(tuple.Left, tuple.Right));

    context.RegisterSourceOutput(missingContractAssemblies, static (spc, missing) =>
    {
      foreach (string detail in missing)
      {
        spc.ReportDiagnostic(Diagnostic.Create(
          DiagnosticDescriptors.ApiEndpointContractAssembliesInvalid,
          Location.None,
          detail));
      }
    });

    // Discover equatable emit models (no INamedTypeSymbol in the collected model).
    IncrementalValuesProvider<EndpointEmitModel> candidates =
      context.CompilationProvider
        .Combine(generationOptions)
        .SelectMany(
          static (tuple, _) =>
          {
            (Compilation compilation, GenerationOptions genOptions) = tuple;
            if (!genOptions.Enabled || genOptions.ContractAssemblies.IsDefaultOrEmpty)
            {
              return ImmutableArray<EndpointEmitModel>.Empty;
            }

            return DiscoverCandidates(compilation, genOptions.ContractAssemblies);
          });

    IncrementalValueProvider<ImmutableArray<EndpointEmitModel>> batch = candidates.Collect();

    IncrementalValueProvider<bool> fastEndpointsAvailable =
      context.CompilationProvider.Select(
        static (compilation, _) =>
        {
          INamedTypeSymbol? fastEndpointsSymbol =
            compilation.GetTypeByMetadataName("FastEndpoints.IEndpoint");
          INamedTypeSymbol? baseFastEndpointSymbol =
            compilation.GetTypeByMetadataName("TimeWarp.Foundation.Features.BaseFastEndpoint`2");
          return fastEndpointsSymbol is not null && baseFastEndpointSymbol is not null;
        });

    IncrementalValueProvider<(ImmutableArray<EndpointEmitModel> Models, bool FeAvailable, GenerationOptions Options)> input =
      batch.Combine(fastEndpointsAvailable).Combine(generationOptions)
        .Select(static (tuple, _) =>
        {
          ((ImmutableArray<EndpointEmitModel> models, bool feAvailable), GenerationOptions options) = tuple;
          return (models, feAvailable, options);
        });

    context.RegisterSourceOutput(input, static (spc, data) => ProcessBatch(spc, data.Models, data.FeAvailable, data.Options));
  }

  private static ImmutableArray<string> FindMissingContractAssemblies(
    Compilation compilation,
    GenerationOptions options)
  {
    if (!options.Enabled)
    {
      return ImmutableArray<string>.Empty;
    }

    if (options.ContractAssemblies.IsDefaultOrEmpty)
    {
      return ImmutableArray.Create(
        "the property is empty or unset; set it to the hosted contracts AssemblyName (web-contracts, api-contracts)");
    }

    var markedNames = HostedRouteDiscovery.GetMarkedReferencedAssemblies(compilation)
      .Select(static assembly => assembly.Name)
      .ToImmutableHashSet(StringComparer.OrdinalIgnoreCase);

    ImmutableArray<string>.Builder missing = ImmutableArray.CreateBuilder<string>();
    foreach (string configured in options.ContractAssemblies)
    {
      if (!markedNames.Contains(configured))
      {
        missing.Add(
          $"'{configured}' matches no marked referenced assembly (typo, renamed AssemblyName, or missing [assembly: ApiEndpointsEmbedded])");
      }
    }

    return missing.ToImmutable();
  }

  private static ImmutableArray<EndpointEmitModel> DiscoverCandidates(
    Compilation compilation,
    ImmutableArray<string> contractAssemblies)
  {
    INamedTypeSymbol? apiEndpointAttributeSymbol =
      compilation.GetTypeByMetadataName(HostedRouteDiscovery.ApiEndpointAttributeFullName);
    if (apiEndpointAttributeSymbol is null)
    {
      return ImmutableArray<EndpointEmitModel>.Empty;
    }

    var allowed = contractAssemblies.ToImmutableHashSet(StringComparer.OrdinalIgnoreCase);

    ImmutableArray<EndpointEmitModel>.Builder builder = ImmutableArray.CreateBuilder<EndpointEmitModel>();

    foreach (IAssemblySymbol assembly in HostedRouteDiscovery.GetMarkedReferencedAssemblies(compilation))
    {
      if (!allowed.Contains(assembly.Name))
      {
        continue;
      }

      foreach (INamespaceSymbol ns in HostedRouteDiscovery.GetAllNamespaces(assembly.GlobalNamespace))
      {
        foreach (INamedTypeSymbol type in ns.GetTypeMembers())
        {
          bool hasApiEndpoint = type.GetAttributes().Any(attr =>
            SymbolEqualityComparer.Default.Equals(attr.AttributeClass, apiEndpointAttributeSymbol)
            || attr.AttributeClass?.Name == HostedRouteDiscovery.ApiEndpointAttributeSimpleName);
          if (!hasApiEndpoint)
          {
            continue;
          }

          INamedTypeSymbol? requestClass = type.GetTypeMembers()
            .FirstOrDefault(static m => m.Name is "Query" or "Command");

          // ClientOnly on outer or nested → not hosted (TWA0020 warns separately).
          if (HostedRouteDiscovery.HasClientOnlyOnOperationOrRequest(type, requestClass))
          {
            continue;
          }

          builder.Add(EndpointEmitModel.FromSymbol(type));
        }
      }
    }

    builder.Sort(static (left, right) =>
    {
      int namespaceOrder = string.CompareOrdinal(left.Namespace, right.Namespace);
      return namespaceOrder != 0
        ? namespaceOrder
        : string.CompareOrdinal(left.ClassName, right.ClassName);
    });

    return builder.ToImmutable();
  }

  private static void ProcessBatch(
    SourceProductionContext spc,
    ImmutableArray<EndpointEmitModel> models,
    bool feAvailable,
    GenerationOptions options)
  {
    if (!options.Enabled)
    {
      return;
    }

    if (!feAvailable)
    {
      spc.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.MissingFastEndpoints, Location.None));
      return;
    }

    try
    {
      // Phase 1: per-contract shape diagnostics (TWE002 / TWE007); only valid models emit.
      var emitCandidates = new List<EndpointEmitModel>();

      foreach (EndpointEmitModel model in models)
      {
        if (model.MissingQueryOrCommand)
        {
          spc.ReportDiagnostic(Diagnostic.Create(
            DiagnosticDescriptors.ApiEndpointMissingQuery,
            Location.None,
            model.ClassName));
          continue;
        }

        if (model.VerbUnresolved || string.IsNullOrEmpty(model.HttpVerb) || string.IsNullOrWhiteSpace(model.Route))
        {
          spc.ReportDiagnostic(Diagnostic.Create(
            DiagnosticDescriptors.ApiEndpointUnknownHttpVerb,
            Location.None,
            model.ClassName,
            string.IsNullOrEmpty(model.UnresolvedVerbDisplay)
              ? (string.IsNullOrWhiteSpace(model.Route) ? "<empty route>" : "<missing>")
              : model.UnresolvedVerbDisplay));
          continue;
        }

        emitCandidates.Add(model);
      }

      // Phase 2: route+verb conflict groups — TWE003 on ALL parties; generate NONE of the group.
      var groups = emitCandidates
        .GroupBy(static m => (m.Route, m.HttpVerb), RouteVerbComparer.Instance)
        .ToList();

      foreach (IGrouping<(string Route, string HttpVerb), EndpointEmitModel> group in groups)
      {
        var parties = group.ToList();
        if (parties.Count > 1)
        {
          string allNames = string.Join(", ", parties.Select(static p => p.ClassName).OrderBy(static n => n, StringComparer.Ordinal));
          foreach (EndpointEmitModel party in parties)
          {
            spc.ReportDiagnostic(Diagnostic.Create(
              DiagnosticDescriptors.ApiEndpointRouteConflict,
              Location.None,
              party.Route,
              party.HttpVerb,
              allNames));
          }

          continue;
        }

        EndpointEmitModel model = parties[0];
        string endpointClass = GenerateEndpointClass(model);
        string fileName = $"{model.ClassName}Endpoint.g.cs";
        spc.AddSource(fileName, SourceText.From(endpointClass, Encoding.UTF8));
      }
    }
    catch (Exception ex) // CA1031: Source generators must be resilient
    {
      spc.ReportDiagnostic(Diagnostic.Create(
        DiagnosticDescriptors.SourceGeneratorLog,
        Location.None,
        $"Error generating endpoints: {ex.Message}"));
    }
  }

  private static string GenerateEndpointClass(EndpointEmitModel metadata)
  {
    // FE Tags() = endpoint-filter metadata only. OpenAPI/Scalar need Description.WithTags.
    string tagArgs = metadata.Tags.Length > 0
      ? string.Join(", ", metadata.Tags.Select(static t => $"\"{t}\""))
      : string.Empty;

    string tagsFilter = metadata.Tags.Length > 0
      ? $"Tags({tagArgs});"
      : "";

    string auth = BuildAuthConfiguration(metadata);

    // FE default RequestBinder TypeInit-fails on DTOs with zero public properties.
    string emptyBinder = metadata.IsEmptyRequest
      ? $"RequestBinder(new EmptyRequestBinder<{metadata.ClassName}.{metadata.RequestTypeName}>());"
      : "";

    // Fold OpenAPI WithTags into Description when Produces is also emitted; otherwise emit tags alone.
    string withTagsChain = metadata.Tags.Length > 0
      ? $".WithTags({tagArgs})"
      : "";

    string summary = !string.IsNullOrEmpty(metadata.Summary)
      ? $$"""
            Summary(s =>
            {
              s.Summary = "{{EscapeForStringLiteral(metadata.Summary)}}";
              s.Description = "{{EscapeForStringLiteral(metadata.Description)}}";
            });

            Description(d => d{{withTagsChain}}.Produces<{{metadata.ClassName}}.Response>(200, "Success").ProducesProblem(400, "Bad Request")
            );
          """
      : metadata.Tags.Length > 0
        ? $$"""
            Description(d => d.WithTags({{tagArgs}}));
          """
        : "";

    string requestType = metadata.RequestTypeName;

    return $$"""
             using FastEndpoints;
             using OneOf;
             using System.Threading;
             using System.Threading.Tasks;
             using TimeWarp.Foundation.Features;

             namespace {{metadata.Namespace}};

             /// <summary>
             /// {{metadata.Summary}}
             /// </summary>
             /// <remarks>
             /// {{metadata.Description}}
             /// </remarks>
             public class {{metadata.ClassName}}Endpoint : BaseFastEndpoint<{{metadata.ClassName}}.{{requestType}}, {{metadata.ClassName}}.Response>
             {
               public override void Configure()
               {
                 {{metadata.HttpVerb}}("{{metadata.Route}}");
                 {{auth}}
                 {{emptyBinder}}
                 {{tagsFilter}}
                 {{summary}}
               }
             }
             """;
  }

  /// <summary>
  /// Builds FastEndpoints Configure() auth lines from [EndpointAuthorize]/[EndpointAllowAnonymous]
  /// metadata. Task 110 fail-closed default: metadata.AllowAnonymous is true ONLY when
  /// [EndpointAllowAnonymous] was present (see EndpointEmitModel.FromSymbol) — in that case emit
  /// AllowAnonymous(). Otherwise: Policy → Policies(...); Roles → Roles(...);
  /// Schemes → AuthSchemes(...); and if NONE of those were set this method emits NOTHING —
  /// FE requires auth by default when AllowAnonymous() is never called.
  /// </summary>
  private static string BuildAuthConfiguration(EndpointEmitModel metadata)
  {
    if (metadata.AllowAnonymous)
    {
      return "AllowAnonymous();";
    }

    var lines = new List<string>();

    if (!string.IsNullOrEmpty(metadata.AuthenticationSchemes))
    {
      lines.Add($"AuthSchemes({FormatCsvStringArgs(metadata.AuthenticationSchemes)});");
    }

    if (!string.IsNullOrEmpty(metadata.AuthorizationPolicy))
    {
      lines.Add($"Policies(\"{EscapeForStringLiteral(metadata.AuthorizationPolicy)}\");");
    }
    else if (!string.IsNullOrEmpty(metadata.Roles))
    {
      lines.Add($"Roles({FormatCsvStringArgs(metadata.Roles)});");
    }

    return lines.Count > 0
      ? string.Join("\n         ", lines)
      : string.Empty;
  }

  private static string FormatCsvStringArgs(string csv)
  {
    IEnumerable<string> parts = csv
      .Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
      .Select(part => $"\"{EscapeForStringLiteral(part)}\"");
    return string.Join(", ", parts);
  }

  private static string EscapeForStringLiteral(string value)
    => value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);

  private sealed class GenerationOptions : IEquatable<GenerationOptions>
  {
    public bool Enabled { get; }
    public ImmutableArray<string> ContractAssemblies { get; }

    private GenerationOptions(bool enabled, ImmutableArray<string> contractAssemblies)
    {
      Enabled = enabled;
      ContractAssemblies = contractAssemblies;
    }

    public static GenerationOptions Read(AnalyzerConfigOptions globalOptions)
    {
      bool enabled = false;
      if (globalOptions.TryGetValue("build_property.EnableApiEndpointGeneration", out string? enableValue) &&
          bool.TryParse(enableValue, out bool parsed))
      {
        enabled = parsed;
      }

      ImmutableArray<string> contractAssemblies = ImmutableArray<string>.Empty;
      if (globalOptions.TryGetValue("build_property.ApiEndpointContractAssemblies", out string? assembliesValue) &&
          !string.IsNullOrWhiteSpace(assembliesValue))
      {
        contractAssemblies = assembliesValue
          .Split([';', ','], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
          .Distinct(StringComparer.OrdinalIgnoreCase)
          .OrderBy(static name => name, StringComparer.OrdinalIgnoreCase)
          .ToImmutableArray();
      }

      return new GenerationOptions(enabled, contractAssemblies);
    }

    public bool Equals(GenerationOptions? other)
      => other is not null
         && Enabled == other.Enabled
         && ContractAssemblies.SequenceEqual(other.ContractAssemblies, StringComparer.OrdinalIgnoreCase);

    public override bool Equals(object? obj) => Equals(obj as GenerationOptions);

    public override int GetHashCode()
    {
      HashCode hashCode = new();
      hashCode.Add(Enabled);
      foreach (string name in ContractAssemblies)
      {
        hashCode.Add(name, StringComparer.OrdinalIgnoreCase);
      }

      return hashCode.ToHashCode();
    }
  }

  /// <summary>Ordinal route + verb grouping (case-sensitive path match as declared on the contract).</summary>
  private sealed class RouteVerbComparer : IEqualityComparer<(string Route, string HttpVerb)>
  {
    public static readonly RouteVerbComparer Instance = new();

    public bool Equals((string Route, string HttpVerb) x, (string Route, string HttpVerb) y)
      => string.Equals(x.Route, y.Route, StringComparison.Ordinal)
         && string.Equals(x.HttpVerb, y.HttpVerb, StringComparison.Ordinal);

    public int GetHashCode((string Route, string HttpVerb) obj)
      => HashCode.Combine(
        StringComparer.Ordinal.GetHashCode(obj.Route),
        StringComparer.Ordinal.GetHashCode(obj.HttpVerb));
  }
}
