#region Purpose
// Generates the MockWebApiService factory registry from every contract exposing GetMockResponseFactory().
#endregion

#region Design
// Removes the hand-maintained Dictionary<Type, Delegate> registration step (a contract could
// define a factory that was never registered — agreement by memory). The registry is derived:
// any referenced *contracts* assembly type with a public static parameterless
// GetMockResponseFactory() and a nested Query/Command gets an entry keyed by that request type.
// Emission is gated on the compilation declaring a MockWebApiService class (the SPA), so server
// projects that also reference contracts get nothing. The per-feature "use the real API while
// developing" affordance moves from commenting dictionary lines to the hand-written
// UseRealApi set in mock-web-api-service.cs. Entries are sorted for deterministic output.
#endregion

namespace TimeWarp.Architecture.Analyzers;

using System.Collections.Generic;

[Generator]
public sealed class MockResponseFactoryRegistryGenerator : IIncrementalGenerator
{
  private const string HostTypeName = "MockWebApiService";
  private const string FactoryMethodName = "GetMockResponseFactory";

  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    context.RegisterSourceOutput(context.CompilationProvider, static (spc, compilation) => Execute(spc, compilation));
  }

  private static void Execute(SourceProductionContext context, Compilation compilation)
  {
    INamedTypeSymbol? host = compilation.GetSymbolsWithName(HostTypeName, SymbolFilter.Type)
      .OfType<INamedTypeSymbol>()
      .FirstOrDefault();
    if (host is null) return;

    var entries = new List<(string RequestType, string Shell)>();

    IEnumerable<IAssemblySymbol> assemblies = compilation.SourceModule.ReferencedAssemblySymbols
      .Where(static a => a.Name.Contains("contracts", System.StringComparison.OrdinalIgnoreCase))
      .Concat(new[] { (IAssemblySymbol)compilation.Assembly });

    foreach (IAssemblySymbol assembly in assemblies)
    {
      foreach (INamedTypeSymbol type in GetAllTypes(assembly.GlobalNamespace))
      {
        bool hasFactory = type.GetMembers(FactoryMethodName).OfType<IMethodSymbol>()
          .Any(static m => m is { IsStatic: true, Parameters.Length: 0, DeclaredAccessibility: Accessibility.Public });
        if (!hasFactory) continue;

        INamedTypeSymbol? request = type.GetTypeMembers()
          .FirstOrDefault(static t => t.Name is "Query" or "Command");
        if (request is null) continue;

        entries.Add((
          request.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
          type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
      }
    }

    entries.Sort(static (a, b) => string.CompareOrdinal(a.RequestType, b.RequestType));

    var sb = new StringBuilder();
    sb.Append("// <auto-generated/>\n#nullable enable\n");
    sb.Append("namespace ").Append(host.ContainingNamespace.ToDisplayString()).Append(";\n\n");
    sb.Append("internal static class GeneratedMockResponseFactories\n{\n");
    sb.Append("  internal static global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Delegate> Create() =>\n");
    sb.Append("    new()\n    {\n");
    foreach ((string requestType, string shell) in entries)
    {
      sb.Append("      { typeof(").Append(requestType).Append("), ")
        .Append(shell).Append('.').Append(FactoryMethodName).Append("() },\n");
    }

    sb.Append("    };\n}\n");

    context.AddSource("GeneratedMockResponseFactories.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
  }

  private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol root)
  {
    foreach (INamespaceOrTypeSymbol member in root.GetMembers())
    {
      switch (member)
      {
        case INamespaceSymbol ns:
          foreach (INamedTypeSymbol nested in GetAllTypes(ns)) yield return nested;
          break;
        case INamedTypeSymbol type:
          yield return type;
          break;
      }
    }
  }
}
