#region Purpose
// Roslyn replacement for the web-spa StateAccessMixin Moxy mixin (task 053).
// For each state class marked [StateAccessMixin], generates strongly-typed accessors into the shared
// BaseComponent and BaseHandler<TAction> partials so components/handlers can read state by type.
#endregion

namespace TimeWarp.Architecture.Analyzers;

using System.Collections.Generic;

[Generator]
public sealed class StateAccessSourceGenerator : IIncrementalGenerator
{
  private const string AttributeName = "StateAccessMixin";

  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    // The marker attribute and the BaseComponent/BaseHandler partials live in the consumer's
    // RootNamespace (and RootNamespace.Features) — matching the Moxy mixin after sourceName substitution.
    IncrementalValueProvider<string> rootNamespace = context.AnalyzerConfigOptionsProvider.Select(
      static (p, _) => Sanitize(p.GlobalOptions.TryGetValue("build_property.RootNamespace", out string? ns) && !string.IsNullOrWhiteSpace(ns)
        ? ns!
        : "GeneratedMixins"));

    context.RegisterSourceOutput(rootNamespace, static (spc, ns) =>
      spc.AddSource("StateAccessMixinAttribute.g.cs", SourceText.From(BuildAttribute(ns), Encoding.UTF8)));

    IncrementalValuesProvider<State> states = context.SyntaxProvider.CreateSyntaxProvider(
      predicate: static (node, _) => node is ClassDeclarationSyntax c && c.AttributeLists.Count > 0,
      transform: static (ctx, ct) => GetState(ctx, ct))
      .Where(static s => s is not null)
      .Select(static (s, _) => s!.Value);

    context.RegisterSourceOutput(states.Combine(rootNamespace), static (spc, pair) =>
      spc.AddSource($"{pair.Left.HintName}.StateAccess.g.cs", SourceText.From(Emit(pair.Left, pair.Right), Encoding.UTF8)));
  }

  private readonly struct State
  {
    public State(string fullName, string simpleName, string hintName)
    {
      FullName = fullName;
      SimpleName = simpleName;
      HintName = hintName;
    }

    public string FullName { get; }    // global::Namespace.StateClass
    public string SimpleName { get; }  // StateClass
    public string HintName { get; }
  }

  private static State? GetState(GeneratorSyntaxContext ctx, System.Threading.CancellationToken ct)
  {
    var cls = (ClassDeclarationSyntax)ctx.Node;

    bool marked = cls.AttributeLists
      .SelectMany(static l => l.Attributes)
      .Any(static a => StripAttribute(a.Name.ToString()) == AttributeName);

    if (!marked) return null;

    if (ctx.SemanticModel.GetDeclaredSymbol(cls, ct) is not INamedTypeSymbol symbol) return null;

    string fullName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    string hint = fullName.Replace("global::", string.Empty, System.StringComparison.Ordinal);
    return new State(fullName, symbol.Name, hint);
  }

  private static string Emit(State state, string rootNamespace)
  {
    var sb = new StringBuilder();
    sb.Append("// <auto-generated/>\n");
    sb.Append("namespace ").Append(rootNamespace).Append(".Features;\n\n");

    sb.Append("public partial class BaseComponent\n{\n");
    sb.Append("  internal ").Append(state.FullName).Append(' ').Append(state.SimpleName)
      .Append(" => GetState<").Append(state.FullName).Append(">();\n");
    sb.Append("  internal ").Append(state.FullName).Append(" NoSub").Append(state.SimpleName)
      .Append(" => GetState<").Append(state.FullName).Append(">(false);\n");
    sb.Append("}\n\n");

    sb.Append("internal abstract partial class BaseHandler<TAction>\n{\n");
    sb.Append("  protected ").Append(state.FullName).Append(' ').Append(state.SimpleName)
      .Append(" => Store.GetState<").Append(state.FullName).Append(">();\n");
    sb.Append("}\n");

    return sb.ToString();
  }

  private static string BuildAttribute(string ns)
  {
    var sb = new StringBuilder();
    sb.Append("// <auto-generated/>\n");
    sb.Append("namespace ").Append(ns).Append("\n{\n");
    sb.Append("    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, AllowMultiple = true)]\n");
    sb.Append("    internal sealed class StateAccessMixinAttribute : System.Attribute { }\n");
    sb.Append("}\n");
    return sb.ToString();
  }

  private static string StripAttribute(string name)
  {
    int dot = name.LastIndexOf('.');
    if (dot >= 0) name = name.Substring(dot + 1);
    return name.EndsWith("Attribute", System.StringComparison.Ordinal) ? name.Substring(0, name.Length - "Attribute".Length) : name;
  }

  private static string Sanitize(string ns)
  {
    var sb = new StringBuilder(ns.Length);
    foreach (char c in ns)
      sb.Append(char.IsLetterOrDigit(c) || c == '.' || c == '_' ? c : '_');
    return sb.ToString();
  }
}
