#region Purpose
// Emits the house typed-id BCL surface (Value/New/From/Json/Parse/TypeConverter) onto [TypedId]
// readonly partial record structs, and EF ValueConverters into assemblies that reference EF Core.
#endregion

#region Design
// Attribute is post-init public (TimeWarp.Architecture.TypedIdAttribute) so EF-host compilations can
// see it on referenced id types via metadata; matching is by simple name so each declaring assembly
// can carry its own copy without a shared Attributes package dependency.
// BCL members generate only for source-declared [TypedId] types in the current compilation —
// keeps TimeWarp.Identity dependency-free (System.Text.Json / TypeConverter only).
// EF artifacts generate only when ValueConverter is in the compilation, and cover this compilation
// plus referenced assemblies so hosts call one ConfigureTypedIdConventions instead of hand-registering.
// Invalid shapes (not partial/readonly record struct) are skipped silently for v1.
// Record-struct equality stays compiler-synthesized — do not emit Equals/GetHashCode/==/!=.
// Comparison operators (< <= > >=) are emitted for CA1036 once IComparable is implemented.
#endregion

namespace TimeWarp.Architecture.Analyzers;

using System.Collections.Generic;

[Generator]
public sealed class TypedIdSourceGenerator : IIncrementalGenerator
{
  private const string AttributeSimpleName = "TypedId";
  private const string ValueConverterMetadataName =
    "Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2";
  private const string EfNamespace = "TimeWarp.Architecture.TypedIds.Ef";

  private const string AttributeSource =
    """
    // <auto-generated/>
    #nullable enable
    namespace TimeWarp.Architecture;

    [System.AttributeUsage(System.AttributeTargets.Struct, Inherited = false)]
    public sealed class TypedIdAttribute : System.Attribute
    {
    }
    """;

  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    context.RegisterPostInitializationOutput(static ctx =>
      ctx.AddSource("TypedIdAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

    IncrementalValuesProvider<TypedIdModel> sourceTypedIds = context.SyntaxProvider
      .CreateSyntaxProvider(
        predicate: static (node, _) => IsCandidate(node),
        transform: static (ctx, ct) => GetSourceTypedId(ctx, ct))
      .Where(static m => m is not null)
      .Select(static (m, _) => m!.Value);

    context.RegisterSourceOutput(sourceTypedIds, static (spc, model) =>
    {
      try
      {
        spc.AddSource($"{model.HintName}.TypedId.g.cs", SourceText.From(EmitBcl(model), Encoding.UTF8));
      }
      catch (Exception ex) // CA1031: source generators must be resilient
      {
        spc.ReportDiagnostic(Diagnostic.Create(
          new DiagnosticDescriptor(
            "SG010",
            "TypedId generator error",
            "Error generating TypedId BCL surface for {0}: {1}",
            "SourceGenerator",
            DiagnosticSeverity.Warning,
            isEnabledByDefault: true),
          Location.None,
          model.Name,
          ex.Message));
      }
    });

    context.RegisterSourceOutput(context.CompilationProvider, static (spc, compilation) =>
    {
      try
      {
        EmitEfIfNeeded(spc, compilation);
      }
      catch (Exception ex) // CA1031: source generators must be resilient
      {
        spc.ReportDiagnostic(Diagnostic.Create(
          new DiagnosticDescriptor(
            "SG011",
            "TypedId EF generator error",
            "Error generating TypedId EF converters: {0}",
            "SourceGenerator",
            DiagnosticSeverity.Warning,
            isEnabledByDefault: true),
          Location.None,
          ex.Message));
      }
    });
  }

  private readonly struct TypedIdModel
  {
    public TypedIdModel(string name, string fullyQualifiedName, string namespaceName, string hintName)
    {
      Name = name;
      FullyQualifiedName = fullyQualifiedName;
      NamespaceName = namespaceName;
      HintName = hintName;
    }

    public string Name { get; }
    public string FullyQualifiedName { get; }
    public string NamespaceName { get; }
    public string HintName { get; }
  }

  private static bool IsCandidate(SyntaxNode node) =>
    node is RecordDeclarationSyntax { AttributeLists.Count: > 0 } record
    && record.IsKind(SyntaxKind.RecordStructDeclaration);

  private static TypedIdModel? GetSourceTypedId(GeneratorSyntaxContext context, CancellationToken cancellationToken)
  {
    var record = (RecordDeclarationSyntax)context.Node;

    if (!HasTypedIdAttribute(record.AttributeLists))
      return null;

    if (!record.Modifiers.Any(SyntaxKind.PartialKeyword) || !record.Modifiers.Any(SyntaxKind.ReadOnlyKeyword))
      return null;

    if (context.SemanticModel.GetDeclaredSymbol(record, cancellationToken) is not INamedTypeSymbol symbol)
      return null;

    if (!IsValidTypedIdShape(symbol))
      return null;

    return ToModel(symbol);
  }

  private static bool IsValidTypedIdShape(INamedTypeSymbol symbol) =>
    symbol is { TypeKind: TypeKind.Struct, IsRecord: true, IsReadOnly: true, IsGenericType: false };

  private static TypedIdModel ToModel(INamedTypeSymbol symbol)
  {
    string fullyQualified = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    string hint = fullyQualified.Replace("global::", string.Empty, StringComparison.Ordinal)
      .Replace('.', '_');
    string ns = symbol.ContainingNamespace.IsGlobalNamespace
      ? string.Empty
      : symbol.ContainingNamespace.ToDisplayString();
    return new TypedIdModel(symbol.Name, fullyQualified, ns, hint);
  }

  private static bool HasTypedIdAttribute(SyntaxList<AttributeListSyntax> attributeLists) =>
    attributeLists
      .SelectMany(static list => list.Attributes)
      .Any(static attribute => IsTypedIdAttributeName(attribute.Name.ToString()));

  private static bool IsTypedIdAttributeName(string name)
  {
    int dot = name.LastIndexOf('.');
    if (dot >= 0)
      name = name.Substring(dot + 1);

    return name is AttributeSimpleName or AttributeSimpleName + "Attribute";
  }

  private static bool HasTypedIdAttribute(INamedTypeSymbol type) =>
    type.GetAttributes().Any(static attr =>
    {
      string? name = attr.AttributeClass?.Name;
      return name is AttributeSimpleName or AttributeSimpleName + "Attribute";
    });

  private static string EmitBcl(TypedIdModel model)
  {
    string ns = model.NamespaceName;
    string name = model.Name;
    string nsOpen = string.IsNullOrEmpty(ns) ? string.Empty : $"namespace {ns};\n\n";

    return $$"""
      // <auto-generated/>
      #nullable enable
      using System;
      using System.ComponentModel;
      using System.Diagnostics.CodeAnalysis;
      using System.Globalization;
      using System.Text.Json;
      using System.Text.Json.Serialization;

      {{nsOpen}}[JsonConverter(typeof({{name}}JsonConverter))]
      [TypeConverter(typeof({{name}}TypeConverter))]
      public readonly partial record struct {{name}} :
        IComparable<{{name}}>,
        IParsable<{{name}}>,
        ISpanParsable<{{name}}>
      {
        public Guid Value { get; }
        public bool IsEmpty => Value == Guid.Empty;

        private {{name}}(Guid value) => Value = value;

        public static {{name}} New() => new(Guid.CreateVersion7());

        public static {{name}} From(Guid value)
        {
          if (value == Guid.Empty)
            throw new ArgumentException("{{name}} cannot be empty.", nameof(value));
          return new {{name}}(value);
        }

        public int CompareTo({{name}} other) => Value.CompareTo(other.Value);

        public static bool operator <({{name}} left, {{name}} right) => left.CompareTo(right) < 0;
        public static bool operator >({{name}} left, {{name}} right) => left.CompareTo(right) > 0;
        public static bool operator <=({{name}} left, {{name}} right) => left.CompareTo(right) <= 0;
        public static bool operator >=({{name}} left, {{name}} right) => left.CompareTo(right) >= 0;

        public override string ToString() => Value.ToString();

        public static {{name}} Parse(string s, IFormatProvider? provider)
        {
          if (!TryParse(s, provider, out {{name}} result))
            throw new FormatException($"Unable to parse '{s}' as {{name}}.");
          return result;
        }

        public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, out {{name}} result)
        {
          if (Guid.TryParse(s, provider, out Guid g) && g != Guid.Empty)
          {
            result = new {{name}}(g);
            return true;
          }
          result = default;
          return false;
        }

        public static {{name}} Parse(ReadOnlySpan<char> s, IFormatProvider? provider)
        {
          if (!TryParse(s, provider, out {{name}} result))
            throw new FormatException($"Unable to parse value as {{name}}.");
          return result;
        }

        public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out {{name}} result)
        {
          if (Guid.TryParse(s, provider, out Guid g) && g != Guid.Empty)
          {
            result = new {{name}}(g);
            return true;
          }
          result = default;
          return false;
        }

        private sealed class {{name}}JsonConverter : JsonConverter<{{name}}>
        {
          public override {{name}} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
          {
            if (reader.TokenType != JsonTokenType.String)
              throw new JsonException($"Expected string for {{name}}.");
            string? text = reader.GetString();
            if (!Guid.TryParse(text, out Guid g) || g == Guid.Empty)
              throw new JsonException($"{{name}} cannot be empty or invalid.");
            return new {{name}}(g);
          }

          public override void Write(Utf8JsonWriter writer, {{name}} value, JsonSerializerOptions options)
            => writer.WriteStringValue(value.Value);

          public override {{name}} ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
            => Read(ref reader, typeToConvert, options);

          public override void WriteAsPropertyName(Utf8JsonWriter writer, {{name}} value, JsonSerializerOptions options)
            => writer.WritePropertyName(value.Value.ToString());
        }

        private sealed class {{name}}TypeConverter : TypeConverter
        {
          public override bool CanConvertFrom(ITypeDescriptorContext? context, Type sourceType)
            => sourceType == typeof(string) || sourceType == typeof(Guid) || base.CanConvertFrom(context, sourceType);

          public override object? ConvertFrom(ITypeDescriptorContext? context, CultureInfo? culture, object value)
          {
            return value switch
            {
              Guid g => From(g),
              string s when TryParse(s, culture, out {{name}} id) => id,
              _ => base.ConvertFrom(context, culture, value)
            };
          }

          public override bool CanConvertTo(ITypeDescriptorContext? context, [NotNullWhen(true)] Type? destinationType)
            => destinationType == typeof(string) || destinationType == typeof(Guid) || base.CanConvertTo(context, destinationType);

          public override object? ConvertTo(ITypeDescriptorContext? context, CultureInfo? culture, object? value, Type destinationType)
          {
            if (value is {{name}} id)
            {
              if (destinationType == typeof(string)) return id.ToString();
              if (destinationType == typeof(Guid)) return id.Value;
            }
            return base.ConvertTo(context, culture, value, destinationType);
          }
        }
      }
      """;
  }

  private static void EmitEfIfNeeded(SourceProductionContext context, Compilation compilation)
  {
    if (compilation.GetTypeByMetadataName(ValueConverterMetadataName) is null)
      return;

    var typedIds = new List<TypedIdModel>();
    CollectTypedIds(compilation.Assembly.GlobalNamespace, typedIds);

    foreach (IAssemblySymbol assembly in compilation.SourceModule.ReferencedAssemblySymbols)
      CollectTypedIds(assembly.GlobalNamespace, typedIds);

    if (typedIds.Count == 0)
      return;

    typedIds.Sort(static (a, b) => string.CompareOrdinal(a.FullyQualifiedName, b.FullyQualifiedName));

    // De-dupe by fully-qualified name (same type should not appear twice).
    var seen = new HashSet<string>(StringComparer.Ordinal);
    var unique = new List<TypedIdModel>(typedIds.Count);
    foreach (TypedIdModel model in typedIds)
    {
      if (seen.Add(model.FullyQualifiedName))
        unique.Add(model);
    }

    foreach (TypedIdModel model in unique)
    {
      string converterSource = EmitValueConverter(model);
      context.AddSource($"{model.HintName}ValueConverter.g.cs", SourceText.From(converterSource, Encoding.UTF8));
    }

    context.AddSource(
      "TypedIdModelConfigurationBuilderExtensions.g.cs",
      SourceText.From(EmitConfigureExtensions(unique), Encoding.UTF8));
  }

  private static void CollectTypedIds(INamespaceSymbol root, List<TypedIdModel> results)
  {
    foreach (INamedTypeSymbol type in GetAllTypes(root))
    {
      if (!IsValidTypedIdShape(type) || !HasTypedIdAttribute(type))
        continue;

      results.Add(ToModel(type));
    }
  }

  private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol root)
  {
    foreach (INamespaceOrTypeSymbol member in root.GetMembers())
    {
      switch (member)
      {
        case INamespaceSymbol ns:
          foreach (INamedTypeSymbol nested in GetAllTypes(ns))
            yield return nested;
          break;
        case INamedTypeSymbol type:
          yield return type;
          foreach (INamedTypeSymbol nested in GetNestedTypes(type))
            yield return nested;
          break;
      }
    }
  }

  private static IEnumerable<INamedTypeSymbol> GetNestedTypes(INamedTypeSymbol type)
  {
    foreach (INamedTypeSymbol nested in type.GetTypeMembers())
    {
      yield return nested;
      foreach (INamedTypeSymbol deeper in GetNestedTypes(nested))
        yield return deeper;
    }
  }

  private static string EmitValueConverter(TypedIdModel model)
  {
    string name = model.Name;
    string full = model.FullyQualifiedName;

    return $$"""
      // <auto-generated/>
      #nullable enable
      using System;

      namespace {{EfNamespace}};

      internal sealed class {{name}}ValueConverter : Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<{{full}}, Guid>
      {
        public {{name}}ValueConverter() : base(v => v.Value, v => {{full}}.From(v))
        {
        }
      }
      """;
  }

  private static string EmitConfigureExtensions(IReadOnlyList<TypedIdModel> models)
  {
    var sb = new StringBuilder();
    sb.Append("// <auto-generated/>\n");
    sb.Append("#nullable enable\n\n");
    sb.Append("namespace ").Append(EfNamespace).Append(";\n\n");
    sb.Append("internal static class TypedIdModelConfigurationBuilderExtensions\n");
    sb.Append("{\n");
    sb.Append("  public static Microsoft.EntityFrameworkCore.ModelConfigurationBuilder ConfigureTypedIdConventions(\n");
    sb.Append("    this Microsoft.EntityFrameworkCore.ModelConfigurationBuilder configurationBuilder)\n");
    sb.Append("  {\n");

    foreach (TypedIdModel model in models)
    {
      sb.Append("    configurationBuilder.Properties<")
        .Append(model.FullyQualifiedName)
        .Append(">().HaveConversion<")
        .Append(model.Name)
        .Append("ValueConverter>();\n");
    }

    sb.Append("    return configurationBuilder;\n");
    sb.Append("  }\n");
    sb.Append("}\n");
    return sb.ToString();
  }
}
