#region Purpose
// Emits the house typed-id BCL surface (Value/New/From/Json/Parse/TypeConverter) onto [TypedId]
// readonly partial record structs, and EF ValueConverters into assemblies that reference EF Core.
#endregion

#region Design
// Both injected attributes are INTERNAL: each compilation running the generator gets its own copy, so
// nothing is exported and two generator-running assemblies referencing each other cannot collide
// (a public copy caused CS0436 at every [TypedId] usage site — proven by probe, 104-027 review).
// Roslyn reads attribute *applications* from referenced-assembly metadata regardless of the attribute
// class's accessibility, so the EF pass still sees [TypedId] on referenced internal-attributed types.
// Matching is by simple name so each assembly's copy is equivalent.
// A [assembly: TypedIdsEmbedded] marker is stamped whenever a compilation declares typed ids; the EF
// pass walks only marked referenced assemblies instead of the whole reference closure (MSBuild passes
// the transitive closure to the compiler, so ReferencedAssemblySymbols covers transitive references —
// without the marker filter every framework assembly's namespace tree would be walked per run).
// The EF output is keyed on an equatable model (HasEf + sorted id list) so it only regenerates when
// the id set or EF-ness actually changes, not on every compilation edit.
// Referenced-assembly ids are validated by member shape (Value/From), not IsRecord — record structs
// compile to plain structs and IsRecord is false on metadata symbols.
// Invalid shapes (not a readonly partial record struct) report TWE006 as a build error: a silently
// skipped id would still compile as a contract property and serialize fail-open as {} — the exact
// defect this generator exists to close.
// Record-struct equality stays compiler-synthesized — do not emit Equals/GetHashCode/==/!=.
// Comparison operators (< <= > >=) are emitted for CA1036 once IComparable is implemented.
#endregion

namespace TimeWarp.Architecture.Analyzers;

using System.Collections.Generic;

[Generator]
public sealed class TypedIdSourceGenerator : IIncrementalGenerator
{
  private const string AttributeSimpleName = "TypedId";
  private const string MarkerAttributeSimpleName = "TypedIdsEmbeddedAttribute";
  private const string ValueConverterMetadataName =
    "Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2";
  private const string EfNamespace = "TimeWarp.Architecture.TypedIds.Ef";

  private const string AttributeSource =
    """
    // <auto-generated/>
    #nullable enable
    namespace TimeWarp.Architecture;

    [System.AttributeUsage(System.AttributeTargets.Struct, Inherited = false)]
    internal sealed class TypedIdAttribute : System.Attribute
    {
    }

    [System.AttributeUsage(System.AttributeTargets.Assembly, Inherited = false)]
    internal sealed class TypedIdsEmbeddedAttribute : System.Attribute
    {
    }
    """;

  private const string MarkerSource =
    """
    // <auto-generated/>
    [assembly: TimeWarp.Architecture.TypedIdsEmbedded]
    """;

  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    context.RegisterPostInitializationOutput(static ctx =>
      ctx.AddSource("TypedIdAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

    IncrementalValueProvider<ImmutableArray<Candidate>> candidates = context.SyntaxProvider
      .CreateSyntaxProvider(
        predicate: static (node, _) => IsCandidate(node),
        transform: static (ctx, ct) => GetCandidate(ctx, ct))
      .Where(static c => c is not null)
      .Select(static (c, _) => c!.Value)
      .Collect();

    context.RegisterSourceOutput(candidates, static (spc, all) => EmitBclAndMarker(spc, all));

    IncrementalValueProvider<EfModel> efModel = context.CompilationProvider
      .Combine(candidates)
      .Select(static (pair, ct) => BuildEfModel(pair.Left, pair.Right, ct));

    context.RegisterSourceOutput(efModel, static (spc, model) =>
    {
      try
      {
        EmitEf(spc, model);
      }
      catch (Exception ex) // CA1031: source generators must be resilient
      {
        spc.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.TypedIdEfGeneratorError, Location.None, ex.Message));
      }
    });
  }

  private readonly record struct TypedIdModel(
    string Name,
    string FullyQualifiedName,
    string NamespaceName,
    string HintName);

  /// <summary>A [TypedId]-attributed declaration: either a valid model or an invalid shape to report.</summary>
  private readonly record struct Candidate(TypedIdModel? Model, string? InvalidName, Location? InvalidLocation);

  /// <summary>Equatable EF-pass input so the EF output only regenerates when the id set or EF-ness changes.</summary>
  private sealed class EfModel : IEquatable<EfModel>
  {
    public EfModel(bool hasEf, ImmutableArray<TypedIdModel> ids)
    {
      HasEf = hasEf;
      Ids = ids;
    }

    public bool HasEf { get; }
    public ImmutableArray<TypedIdModel> Ids { get; }

    public bool Equals(EfModel? other) =>
      other is not null && HasEf == other.HasEf && Ids.SequenceEqual(other.Ids);

    public override bool Equals(object? obj) => Equals(obj as EfModel);

    public override int GetHashCode()
    {
      int hash = HasEf ? 17 : 31;
      foreach (TypedIdModel model in Ids)
        hash = unchecked((hash * 397) ^ model.FullyQualifiedName.GetHashCode(StringComparison.Ordinal));
      return hash;
    }
  }

  private static bool IsCandidate(SyntaxNode node) => node switch
  {
    StructDeclarationSyntax { AttributeLists.Count: > 0 } => true,
    RecordDeclarationSyntax { AttributeLists.Count: > 0 } record =>
      record.IsKind(SyntaxKind.RecordStructDeclaration),
    _ => false,
  };

  private static Candidate? GetCandidate(GeneratorSyntaxContext context, CancellationToken cancellationToken)
  {
    var declaration = (TypeDeclarationSyntax)context.Node;

    if (!HasTypedIdAttribute(declaration.AttributeLists))
      return null;

    if (context.SemanticModel.GetDeclaredSymbol(declaration, cancellationToken) is not INamedTypeSymbol symbol)
      return null;

    bool isPartial = symbol.DeclaringSyntaxReferences
      .Select(reference => reference.GetSyntax(cancellationToken))
      .OfType<TypeDeclarationSyntax>()
      .Any(static d => d.Modifiers.Any(SyntaxKind.PartialKeyword));

    if (IsValidTypedIdShape(symbol) && isPartial)
      return new Candidate(ToModel(symbol), null, null);

    return new Candidate(null, symbol.Name, declaration.Identifier.GetLocation());
  }

  private static bool IsValidTypedIdShape(INamedTypeSymbol symbol) =>
    symbol is { TypeKind: TypeKind.Struct, IsRecord: true, IsReadOnly: true, IsGenericType: false };

  private static TypedIdModel ToModel(INamedTypeSymbol symbol)
  {
    string fullyQualified = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    string hint = fullyQualified.Replace("global::", string.Empty, StringComparison.Ordinal)
      .Replace('.', '_');
    string ns = symbol.ContainingNamespace.IsGlobalNamespace
      ? string.Empty
      : symbol.ContainingNamespace.ToDisplayString();
    return new TypedIdModel(symbol.Name, fullyQualified, ns, hint);
  }

  private static bool HasTypedIdAttribute(SyntaxList<AttributeListSyntax> attributeLists) =>
    attributeLists
      .SelectMany(static list => list.Attributes)
      .Any(static attribute => IsTypedIdAttributeName(attribute.Name.ToString()));

  private static bool IsTypedIdAttributeName(string name)
  {
    int dot = name.LastIndexOf('.');
    if (dot >= 0)
      name = name.Substring(dot + 1);

    return name is AttributeSimpleName or AttributeSimpleName + "Attribute";
  }

  private static bool HasTypedIdAttribute(INamedTypeSymbol type) =>
    type.GetAttributes().Any(static attr =>
    {
      string? name = attr.AttributeClass?.Name;
      return name is AttributeSimpleName or AttributeSimpleName + "Attribute";
    });

  private static void EmitBclAndMarker(SourceProductionContext context, ImmutableArray<Candidate> candidates)
  {
    var emitted = new HashSet<string>(StringComparer.Ordinal);
    bool anyValid = false;

    foreach (Candidate candidate in candidates)
    {
      if (candidate.Model is not TypedIdModel model)
      {
        context.ReportDiagnostic(Diagnostic.Create(
          DiagnosticDescriptors.TypedIdInvalidShape,
          candidate.InvalidLocation ?? Location.None,
          candidate.InvalidName ?? "<unknown>"));
        continue;
      }

      // Multiple partial declarations of one type each match the syntax provider — emit once.
      if (!emitted.Add(model.FullyQualifiedName))
        continue;

      try
      {
        context.AddSource($"{model.HintName}.TypedId.g.cs", SourceText.From(EmitBcl(model), Encoding.UTF8));
        anyValid = true;
      }
      catch (Exception ex) // CA1031: source generators must be resilient; name the type that failed
      {
        context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.TypedIdBclGeneratorError, Location.None, model.Name, ex.Message));
      }
    }

    if (anyValid)
      context.AddSource("TypedIdsEmbedded.g.cs", SourceText.From(MarkerSource, Encoding.UTF8));
  }

  private static string EmitBcl(TypedIdModel model)
  {
    string ns = model.NamespaceName;
    string name = model.Name;
    string nsOpen = string.IsNullOrEmpty(ns) ? string.Empty : $"namespace {ns};\n\n";

    return $$"""
      // <auto-generated/>
      #nullable enable
      using System;
      using System.ComponentModel;
      using System.Diagnostics.CodeAnalysis;
      using System.Globalization;
      using System.Text.Json;
      using System.Text.Json.Serialization;

      {{nsOpen}}[JsonConverter(typeof({{name}}JsonConverter))]
      [TypeConverter(typeof({{name}}TypeConverter))]
      public readonly partial record struct {{name}} :
        IComparable<{{name}}>,
        IParsable<{{name}}>,
        ISpanParsable<{{name}}>
      {
        public Guid Value { get; }
        public bool IsEmpty => Value == Guid.Empty;

        private {{name}}(Guid value) => Value = value;

        public static {{name}} New() => new(Guid.CreateVersion7());

        public static {{name}} From(Guid value)
        {
          if (value == Guid.Empty)
            throw new ArgumentException("{{name}} cannot be empty.", nameof(value));
          return new {{name}}(value);
        }

        public int CompareTo({{name}} other) => Value.CompareTo(other.Value);

        public static bool operator <({{name}} left, {{name}} right) => left.CompareTo(right) < 0;
        public static bool operator >({{name}} left, {{name}} right) => left.CompareTo(right) > 0;
        public static bool operator <=({{name}} left, {{name}} right) => left.CompareTo(right) <= 0;
        public static bool operator >=({{name}} left, {{name}} right) => left.CompareTo(right) >= 0;

        public override string ToString() => Value.ToString();

        public static {{name}} Parse(string s, IFormatProvider? provider)
        {
          if (!TryParse(s, provider, out {{name}} result))
            throw new FormatException($"Unable to parse '{s}' as {{name}}.");
          return result;
        }

        public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, out {{name}} result)
        {
          if (Guid.TryParse(s, provider, out Guid g) && g != Guid.Empty)
          {
            result = new {{name}}(g);
            return true;
          }
          result = default;
          return false;
        }

        public static {{name}} Parse(ReadOnlySpan<char> s, IFormatProvider? provider)
        {
          if (!TryParse(s, provider, out {{name}} result))
            throw new FormatException($"Unable to parse value as {{name}}.");
          return result;
        }

        public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out {{name}} result)
        {
          if (Guid.TryParse(s, provider, out Guid g) && g != Guid.Empty)
          {
            result = new {{name}}(g);
            return true;
          }
          result = default;
          return false;
        }

        private sealed class {{name}}JsonConverter : JsonConverter<{{name}}>
        {
          public override {{name}} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
          {
            if (reader.TokenType != JsonTokenType.String)
              throw new JsonException($"Expected string for {{name}}.");
            string? text = reader.GetString();
            if (!Guid.TryParse(text, out Guid g) || g == Guid.Empty)
              throw new JsonException($"{{name}} cannot be empty or invalid.");
            return new {{name}}(g);
          }

          public override void Write(Utf8JsonWriter writer, {{name}} value, JsonSerializerOptions options)
            => writer.WriteStringValue(value.Value);

          public override {{name}} ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
            => Read(ref reader, typeToConvert, options);

          public override void WriteAsPropertyName(Utf8JsonWriter writer, {{name}} value, JsonSerializerOptions options)
            => writer.WritePropertyName(value.Value.ToString());
        }

        private sealed class {{name}}TypeConverter : TypeConverter
        {
          public override bool CanConvertFrom(ITypeDescriptorContext? context, Type sourceType)
            => sourceType == typeof(string) || sourceType == typeof(Guid) || base.CanConvertFrom(context, sourceType);

          public override object? ConvertFrom(ITypeDescriptorContext? context, CultureInfo? culture, object value)
          {
            return value switch
            {
              Guid g => From(g),
              string s when TryParse(s, culture, out {{name}} id) => id,
              _ => base.ConvertFrom(context, culture, value)
            };
          }

          public override bool CanConvertTo(ITypeDescriptorContext? context, [NotNullWhen(true)] Type? destinationType)
            => destinationType == typeof(string) || destinationType == typeof(Guid) || base.CanConvertTo(context, destinationType);

          public override object? ConvertTo(ITypeDescriptorContext? context, CultureInfo? culture, object? value, Type destinationType)
          {
            if (value is {{name}} id)
            {
              if (destinationType == typeof(string)) return id.ToString();
              if (destinationType == typeof(Guid)) return id.Value;
            }
            return base.ConvertTo(context, culture, value, destinationType);
          }
        }
      }
      """;
  }

  private static EfModel BuildEfModel(
    Compilation compilation,
    ImmutableArray<Candidate> candidates,
    CancellationToken cancellationToken)
  {
    if (compilation.GetTypeByMetadataName(ValueConverterMetadataName) is null)
      return new EfModel(hasEf: false, ImmutableArray<TypedIdModel>.Empty);

    var typedIds = new List<TypedIdModel>();

    foreach (Candidate candidate in candidates)
    {
      if (candidate.Model is TypedIdModel model)
        typedIds.Add(model);
    }

    // MSBuild passes the transitive reference closure to the compiler, so this covers transitive
    // references too. The marker filter keeps this from walking framework assemblies' namespaces.
    foreach (IAssemblySymbol assembly in compilation.SourceModule.ReferencedAssemblySymbols)
    {
      cancellationToken.ThrowIfCancellationRequested();

      if (!HasEmbeddedMarker(assembly))
        continue;

      CollectTypedIds(assembly.GlobalNamespace, typedIds);
    }

    typedIds.Sort(static (a, b) => string.CompareOrdinal(a.FullyQualifiedName, b.FullyQualifiedName));

    var seen = new HashSet<string>(StringComparer.Ordinal);
    ImmutableArray<TypedIdModel>.Builder unique = ImmutableArray.CreateBuilder<TypedIdModel>(typedIds.Count);
    foreach (TypedIdModel model in typedIds)
    {
      if (seen.Add(model.FullyQualifiedName))
        unique.Add(model);
    }

    return new EfModel(hasEf: true, unique.ToImmutable());
  }

  private static bool HasEmbeddedMarker(IAssemblySymbol assembly) =>
    assembly.GetAttributes().Any(static attr => attr.AttributeClass?.Name == MarkerAttributeSimpleName);

  private static void EmitEf(SourceProductionContext context, EfModel model)
  {
    if (!model.HasEf || model.Ids.IsEmpty)
      return;

    foreach (TypedIdModel id in model.Ids)
    {
      string converterSource = EmitValueConverter(id);
      context.AddSource($"{id.HintName}ValueConverter.g.cs", SourceText.From(converterSource, Encoding.UTF8));
    }

    context.AddSource(
      "TypedIdModelConfigurationBuilderExtensions.g.cs",
      SourceText.From(EmitConfigureExtensions(model.Ids), Encoding.UTF8));
  }

  private static void CollectTypedIds(INamespaceSymbol root, List<TypedIdModel> results)
  {
    foreach (INamedTypeSymbol type in GetAllTypes(root))
    {
      if (!IsValidMetadataTypedId(type) || !HasTypedIdAttribute(type))
        continue;

      results.Add(ToModel(type));
    }
  }

  // IsRecord does not round-trip through metadata for record structs (they compile to plain structs),
  // so referenced-assembly ids are validated by the generated member shape instead. A [TypedId] type in
  // a successfully-built referenced assembly has that shape: TWE006 breaks invalid shapes at its own
  // compile time, and a type that never ran the generator lacks Value/From and fails here.
  private static bool IsValidMetadataTypedId(INamedTypeSymbol type) =>
    type is { TypeKind: TypeKind.Struct, IsGenericType: false }
    && type.GetMembers("Value").OfType<IPropertySymbol>().Any(static p => IsSystemGuid(p.Type))
    && type.GetMembers("From").OfType<IMethodSymbol>().Any(static m =>
      m.IsStatic && m.Parameters.Length == 1 && IsSystemGuid(m.Parameters[0].Type));

  private static bool IsSystemGuid(ITypeSymbol type) =>
    type is INamedTypeSymbol
    {
      Name: "Guid",
      ContainingNamespace: { Name: "System", ContainingNamespace.IsGlobalNamespace: true },
    };

  private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol root)
  {
    foreach (INamespaceOrTypeSymbol member in root.GetMembers())
    {
      switch (member)
      {
        case INamespaceSymbol ns:
          foreach (INamedTypeSymbol nested in GetAllTypes(ns))
            yield return nested;
          break;
        case INamedTypeSymbol type:
          yield return type;
          foreach (INamedTypeSymbol nested in GetNestedTypes(type))
            yield return nested;
          break;
      }
    }
  }

  private static IEnumerable<INamedTypeSymbol> GetNestedTypes(INamedTypeSymbol type)
  {
    foreach (INamedTypeSymbol nested in type.GetTypeMembers())
    {
      yield return nested;
      foreach (INamedTypeSymbol deeper in GetNestedTypes(nested))
        yield return deeper;
    }
  }

  private static string EmitValueConverter(TypedIdModel model)
  {
    string name = model.Name;
    string full = model.FullyQualifiedName;

    return $$"""
      // <auto-generated/>
      #nullable enable
      using System;

      namespace {{EfNamespace}};

      internal sealed class {{name}}ValueConverter : Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<{{full}}, Guid>
      {
        public {{name}}ValueConverter() : base(v => v.Value, v => {{full}}.From(v))
        {
        }
      }
      """;
  }

  private static string EmitConfigureExtensions(ImmutableArray<TypedIdModel> models)
  {
    var sb = new StringBuilder();
    sb.Append("// <auto-generated/>\n");
    sb.Append("#nullable enable\n\n");
    sb.Append("namespace ").Append(EfNamespace).Append(";\n\n");
    sb.Append("internal static class TypedIdModelConfigurationBuilderExtensions\n");
    sb.Append("{\n");
    sb.Append("  public static Microsoft.EntityFrameworkCore.ModelConfigurationBuilder ConfigureTypedIdConventions(\n");
    sb.Append("    this Microsoft.EntityFrameworkCore.ModelConfigurationBuilder configurationBuilder)\n");
    sb.Append("  {\n");

    foreach (TypedIdModel model in models)
    {
      sb.Append("    configurationBuilder.Properties<")
        .Append(model.FullyQualifiedName)
        .Append(">().HaveConversion<")
        .Append(model.Name)
        .Append("ValueConverter>();\n");
    }

    sb.Append("    return configurationBuilder;\n");
    sb.Append("  }\n");
    sb.Append("}\n");
    return sb.ToString();
  }
}
