name: Api-Server Build and Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Source/ContainerApps/Api/Api.Server/Dockerfile
          image: ${{ secrets.REGISTRY_HOSTNAME }}/api-server:{{ .Build.ID }}
          secrets:
          push: true
          tags: user/app:latest

  docker build --progress=plain -f .\Source\ContainerApps\Api\Api.Server\Dockerfile -t $RegistryHost/api-server:1.0.0 .
