@startuml Dependency graph

!theme plain
skinparam ComponentStyle rectangle
left to right direction

' Projects
[Web.Server] #ecf0f1
[Web.Spa] #ecf0f1
[EndToEnd.TestCafe.Tests] #ecf0f1
[EndToEnd.Playwright.Tests] #ecf0f1
[Testing.Common] #ecf0f1
[SourceCodeGenerators] #ecf0f1
[SourceCodeGenerators.Tests] #ecf0f1
[Yarp] #ecf0f1
[Grpc.Server] #ecf0f1
[Grpc.Contracts] #ecf0f1
[Api.Server] #ecf0f1
[Api.Contracts] #ecf0f1
[Web.TypeScript] #ecf0f1
[Web.Spa.Integration.Tests] #ecf0f1
[Web.Server.Integration.Tests] #ecf0f1
[Api.Server.Integration.Tests] #ecf0f1
[Api.Application] #ecf0f1
[Api.Infrastructure] #ecf0f1
[Api.Domain] #ecf0f1
[Common.Application] #ecf0f1
[Common.Contracts] #ecf0f1
[Common.Domain] #ecf0f1
[Common.Infrastructure] #ecf0f1
[Common.Server] #ecf0f1
[TimeWarp.Modules] #ecf0f1
[Web.Application] #ecf0f1
[Web.Domain] #ecf0f1
[Web.Infrastructure] #ecf0f1
[Grpc.Application] #ecf0f1
[Grpc.Domain] #ecf0f1
[Grpc.Infrastructure] #ecf0f1
[TimeWarp.OptionsValidation] #ecf0f1
[Web.Contracts] #ecf0f1

Web.Server --> Common.Server
Web.Server --> Web.Infrastructure
Web.Server --> Web.Spa
Web.Spa --> TimeWarp.OptionsValidation
Web.Spa --> Api.Contracts
Web.Spa --> Grpc.Contracts
Web.Spa --> Web.Contracts
Testing.Common --> Api.Server
Testing.Common --> Web.Server
Testing.Common --> Yarp
Testing.Common --> SourceCodeGenerators
SourceCodeGenerators.Tests --> SourceCodeGenerators
SourceCodeGenerators.Tests --> Testing.Common
Yarp --> Common.Server
Grpc.Server --> Common.Server
Grpc.Server --> Grpc.Infrastructure
Grpc.Contracts --> Common.Contracts
Api.Server --> Common.Server
Api.Server --> Api.Infrastructure
Api.Contracts --> Common.Contracts
Web.Spa.Integration.Tests --> Web.Spa
Web.Spa.Integration.Tests --> Web.Server
Web.Spa.Integration.Tests --> Testing.Common
Web.Server.Integration.Tests --> Web.Contracts
Web.Server.Integration.Tests --> Web.Server
Web.Server.Integration.Tests --> Testing.Common
Api.Server.Integration.Tests --> Api.Server
Api.Server.Integration.Tests --> Api.Contracts
Api.Server.Integration.Tests --> SourceCodeGenerators
Api.Server.Integration.Tests --> Testing.Common
Api.Application --> Common.Application
Api.Application --> TimeWarp.Modules
Api.Application --> Api.Contracts
Api.Application --> Api.Domain
Api.Infrastructure --> Common.Infrastructure
Api.Infrastructure --> Api.Application
Common.Application --> Common.Contracts
Common.Application --> Common.Domain
Common.Application --> TimeWarp.Modules
Common.Infrastructure --> TimeWarp.OptionsValidation
Common.Infrastructure --> Common.Application
Common.Server --> Common.Infrastructure
Web.Application --> Common.Application
Web.Application --> Web.Contracts
Web.Application --> Web.Domain
Web.Domain --> Common.Domain
Web.Infrastructure --> Common.Infrastructure
Web.Infrastructure --> Web.Application
Grpc.Application --> Common.Application
Grpc.Application --> Grpc.Contracts
Grpc.Application --> Grpc.Domain
Grpc.Domain --> Common.Domain
Grpc.Infrastructure --> Common.Infrastructure
Grpc.Infrastructure --> Grpc.Application
Web.Contracts --> Common.Contracts
@enduml
