// ReSharper disable InconsistentNaming
namespace PurposeRegionAnalyzer_;

using Microsoft.CodeAnalysis.CSharp.Testing;
using TimeWarp.Architecture.Analyzers;
using TimeWarp.Architecture.Analyzers.Tests;

public class Should_Enforce_Purpose_Region
{
  private static CSharpAnalyzerTest<PurposeRegionAnalyzer, FixieVerifier> Test(string fileName, string source) =>
    new() { TestState = { Sources = { (fileName, source) } } };

  public static async Task Given_File_Without_Purpose_Region()
  {
    const string Source =
      """
      namespace Contracts;

      public class Widget
      {
        public string Name { get; set; } = null!;
      }
      """;

    DiagnosticResult expectedDiagnostic = new DiagnosticResult(id: "TWPA0004", DiagnosticSeverity.Warning)
      .WithSpan("Widget.cs", 1, 1, 1, 10)
      .WithArguments("Widget.cs");

    CSharpAnalyzerTest<PurposeRegionAnalyzer, FixieVerifier> analyzerTest = new()
    {
      TestState =
      {
        Sources =
        {
          ("Widget.cs", Source)
        }
      }
    };

    analyzerTest.ExpectedDiagnostics.Add(expectedDiagnostic);

    await analyzerTest.RunAsync();
  }

  public static async Task Given_File_With_Purpose_Region_IsClean()
  {
    const string Source =
      """
      #region Purpose
      // A widget shape used to verify the analyzer accepts a top-of-file region.
      #endregion

      namespace Contracts;

      public class Widget
      {
        public string Name { get; set; } = null!;
      }
      """;

    await Test("Widget.cs", Source).RunAsync();
  }

  public static async Task Given_Purpose_Region_Anywhere_In_File_IsClean()
  {
    // Placement is skill guidance, not analyzer scope — a nested region still satisfies the rule.
    const string Source =
      """
      namespace Contracts;

      public class Widget
      {
        #region Purpose
        // Region nested inside the type still counts.
        #endregion
        public string Name { get; set; } = null!;
      }
      """;

    await Test("Widget.cs", Source).RunAsync();
  }

  public static async Task Given_Other_Region_Names_Still_Flagged()
  {
    const string Source =
      """
      #region Design
      // Design alone is not enough; Purpose is the universal requirement.
      #endregion

      namespace Contracts;

      public class Widget;
      """;

    DiagnosticResult expectedDiagnostic = new DiagnosticResult(id: "TWPA0004", DiagnosticSeverity.Warning)
      .WithSpan("Widget.cs", 5, 1, 5, 10)
      .WithArguments("Widget.cs");

    CSharpAnalyzerTest<PurposeRegionAnalyzer, FixieVerifier> analyzerTest = new()
    {
      TestState =
      {
        Sources =
        {
          ("Widget.cs", Source)
        }
      }
    };

    analyzerTest.ExpectedDiagnostics.Add(expectedDiagnostic);

    await analyzerTest.RunAsync();
  }

  public static async Task Given_Generated_File_IsClean()
  {
    // <auto-generated/> header marks the tree generated; GeneratedCodeAnalysisFlags.None skips it.
    const string Source =
      """
      // <auto-generated/>
      namespace Contracts;

      public class Widget;
      """;

    await Test("Widget.g.cs", Source).RunAsync();
  }
}
