apiVersion: apps/v1
kind: Deployment
metadata:
  name: $ApplicationName
  namespace: $POD_IDENTITY_NAMESPACE
  labels:
    app.kubernetes.io/name: $ApplicationName
    app.kubernetes.io/part-of: $ApplicationNamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: $ApplicationName
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $ApplicationName
        app.kubernetes.io/part-of: $ApplicationNamespace
    spec:
      containers:
        - name: $ApplicationName
          image: $ApplicationImage
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          