global using Ardalis.GuardClauses;
global using Azure.Identity;
global using FluentValidation;
global using MediatR;
global using MicroElements.Swashbuckle.FluentValidation.AspNetCore;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.OpenApi.Models;
global using Microsoft.AspNetCore.Mvc.ApplicationParts;
global using OneOf;
global using System.Reflection;

// Solution usings
global using TimeWarp.Architecture.Enumerations;
global using TimeWarp.Architecture.Types;
