// <auto-generated />
// Generated from feature-filename-grammar.json — do not edit. Edit the JSON and rebuild.
#nullable enable
namespace TimeWarp.Architecture.Analyzers;

using System.Collections.Generic;
using System.Collections.Immutable;

/// <summary>SSOT-backed feature filename grammar constants (TWA0015/TWA0016).</summary>
internal static class FeatureFilenameGrammar
{
  /// <summary>Routed layers (own a layer-project Compile glob) PLUS registered-unrouted layers
  /// (e.g. "tests" — matched and validated by TWA0015/TWA0016/the membership guard, but compiled
  /// into no layer project). See feature-filename-grammar.json's "unroutedLayers".</summary>
  public static readonly ImmutableHashSet<string> Layers =
    ImmutableHashSet.Create(System.StringComparer.Ordinal, "contracts", "application", "domain", "infrastructure", "server", "tests");

  public static readonly ImmutableDictionary<string, string> FunctionToLayer =
    ImmutableDictionary.CreateRange(System.StringComparer.Ordinal, new[]
    {
      new KeyValuePair<string, string>("endpoint", "server"),
      new KeyValuePair<string, string>("handler", "application"),
    });

  public static readonly ImmutableArray<string> FunctionsLongestFirst =
    ImmutableArray.CreateRange(new[]
    {
      "endpoint",
      "handler",
    });

  /// <summary>Lowercase family directory names (e.g. "web", "api", "grpc") whose cohesive trees
  /// TWA0015/TWA0016 scope into; sourced from the Web &lt;Exec&gt; invocation's --families
  /// argument (convention-analyzers csproj) and cross-checked by the SSOT drift test.</summary>
  public static readonly ImmutableArray<string> Families =
    ImmutableArray.Create("web", "api", "grpc");
}
