#!/usr/bin/env python3
"""Generate FeatureFilenameGrammar.g.cs and feature-filename-grammar.g.props from SSOT JSON."""
from __future__ import annotations

import json
import sys
from pathlib import Path


def main() -> int:
  if len(sys.argv) != 4:
    print("Usage: generate-feature-filename-grammar.py <json> <out-cs> <out-props>", file=sys.stderr)
    return 1

  json_path = Path(sys.argv[1])
  out_cs = Path(sys.argv[2])
  out_props = Path(sys.argv[3])

  data = json.loads(json_path.read_text(encoding="utf-8"))
  layers: list[str] = data["layers"]
  functions: dict[str, str] = data["functions"]

  for function, layer in functions.items():
    if layer not in layers:
      print(f"Function '{function}' maps to unregistered layer '{layer}'.", file=sys.stderr)
      return 2

  out_cs.parent.mkdir(parents=True, exist_ok=True)
  out_props.parent.mkdir(parents=True, exist_ok=True)

  layer_args = ", ".join(f'"{layer}"' for layer in layers)
  function_entries = "\n".join(
    f'      new KeyValuePair<string, string>("{function}", "{layer}"),'
    for function, layer in sorted(functions.items())
  )
  longest_first = "\n".join(
    f'      "{function}",'
    for function in sorted(functions.keys(), key=lambda f: (-len(f), f))
  )

  cs = f"""// <auto-generated />
// Generated from feature-filename-grammar.json — do not edit. Edit the JSON and rebuild.
#nullable enable
namespace TimeWarp.Architecture.Analyzers;

using System.Collections.Generic;
using System.Collections.Immutable;

/// <summary>SSOT-backed feature filename grammar constants (TWA0015/TWA0016).</summary>
internal static class FeatureFilenameGrammar
{{
  public static readonly ImmutableHashSet<string> Layers =
    ImmutableHashSet.Create(System.StringComparer.Ordinal, {layer_args});

  public static readonly ImmutableDictionary<string, string> FunctionToLayer =
    ImmutableDictionary.CreateRange(System.StringComparer.Ordinal, new[]
    {{
{function_entries}
    }});

  public static readonly ImmutableArray<string> FunctionsLongestFirst =
    ImmutableArray.CreateRange(new[]
    {{
{longest_first}
    }});
}}
"""
  out_cs.write_text(cs, encoding="utf-8")

  layer_items = "\n".join(
    f'    <FeatureFilenameGrammarLayer Include="{layer}" />' for layer in layers
  )
  function_items = "\n".join(
    f'    <FeatureFilenameGrammarFunction Include="{function}" Layer="{layer}" />'
    for function, layer in sorted(functions.items())
  )
  props = f"""<!--
  AUTO-GENERATED from source/analyzers/timewarp-architecture-convention-analyzers/feature-filename-grammar.json
  Do not edit by hand. Edit the JSON and rebuild the convention-analyzers project (or run the generator).
  Registry edit ⇒ full rebuild (analyzer incremental staleness).
-->
<Project>
  <ItemGroup>
{layer_items}
{function_items}
  </ItemGroup>
</Project>
"""
  out_props.write_text(props, encoding="utf-8")
  print(f"Generated {out_cs}")
  print(f"Generated {out_props}")
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
