#!/usr/bin/env python3
"""Generate FeatureFilenameGrammar.g.cs and a family's feature-filename-grammar.g.props from SSOT JSON.

The JSON registry (layers, unroutedLayers, functions) is family-agnostic. --out-cs emits the
family-agnostic FeatureFilenameGrammar.g.cs registry consumed by the TWA0015/TWA0016 analyzer;
pass it from exactly one per-family invocation (conventionally Web) since the .g.cs is shared,
not per-family.
--out-cs also requires --families (the full lowercase family list, e.g. web,api,grpc) so the
.g.cs carries a Families constant the analyzer derives its per-family path markers from — the
csproj's Web <Exec> line is the single place that family list is authored (besides the drift
test's own copy).
--out-props always emits a standalone family props file (layer items, function items, hybrid
Compile globs) parameterized by --family-prefix, which drives the emitted property names
({Prefix}FeatureTreeRoot / {Prefix}PlatformTreeRoot) and project-name conditions
({prefix-lower}-{layer}).

"unroutedLayers" (e.g. "tests") register a filename layer suffix that the membership guard and
TWA0015/TWA0016 recognize and validate exactly like a routed layer, but that routes into NO
layer project — no Compile ItemGroup is emitted for it and its FeatureFilenameGrammarLayer item
carries no Project metadata. This is how co-located `-tests.cs` runfiles stay matched-and-
validated by the grammar (orphaned/misnamed files still trip the teaching error, and
`-handler-tests.cs` still trips TWA0015 for free) while compiling into nothing.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def layers_nest(layers: list[str]) -> str | None:
  """Return a human message if any registered -{layer} suffix nests inside another."""
  suffixes = [f"-{layer}" for layer in layers]
  for a in suffixes:
    for b in suffixes:
      if a != b and a.endswith(b):
        return f"Layer suffix '{a}' nests inside '{b}' (dual glob match risk)."
  return None


def parse_args(argv: list[str]) -> argparse.Namespace:
  parser = argparse.ArgumentParser(description=__doc__)
  parser.add_argument("--json", required=True, type=Path, dest="json_path", help="Path to feature-filename-grammar.json (SSOT).")
  parser.add_argument("--out-props", required=True, type=Path, help="Path to this family's feature-filename-grammar.g.props output.")
  parser.add_argument("--family-prefix", required=True, help="PascalCase family prefix driving emitted property/project names, e.g. Web, Api, Grpc.")
  parser.add_argument("--out-cs", type=Path, default=None, help="Optional: also (re)generate the family-agnostic FeatureFilenameGrammar.g.cs. Emit from exactly one invocation per build.")
  parser.add_argument("--families", default=None, help="Comma-separated lowercase family list (e.g. web,api,grpc) baked into FeatureFilenameGrammar.g.cs as the Families constant. Required with --out-cs.")
  args = parser.parse_args(argv)
  if args.out_cs is not None and not args.families:
    parser.error("--families is required when --out-cs is set (the .g.cs Families constant).")
  return args


def main() -> int:
  args = parse_args(sys.argv[1:])

  data = json.loads(args.json_path.read_text(encoding="utf-8"))
  layers: list[str] = data["layers"]
  unrouted_layers: list[str] = data.get("unroutedLayers", [])
  functions: dict[str, str] = data["functions"]

  # Combined set for grammar ACCEPTANCE (regex + analyzer Layers HashSet): a registered-unrouted
  # layer (e.g. "tests") is a valid archetype for TWA0015/TWA0016 and the membership guard, it
  # just routes into no layer project (see compile_groups below, which stays routed-only).
  all_layers: list[str] = layers + [layer for layer in unrouted_layers if layer not in layers]

  for function, layer in functions.items():
    if layer not in layers:
      print(f"Function '{function}' maps to unregistered layer '{layer}'.", file=sys.stderr)
      return 2

  nesting = layers_nest(all_layers)
  if nesting:
    print(nesting, file=sys.stderr)
    return 3

  prefix = args.family_prefix
  prefix_lower = prefix.lower()

  if args.out_cs is not None:
    args.out_cs.parent.mkdir(parents=True, exist_ok=True)

    layer_args = ", ".join(f'"{layer}"' for layer in all_layers)
    function_entries = "\n".join(
      f'      new KeyValuePair<string, string>("{function}", "{layer}"),'
      for function, layer in sorted(functions.items())
    )
    longest_first = "\n".join(
      f'      "{function}",'
      for function in sorted(functions.keys(), key=lambda f: (-len(f), f))
    )

    family_list = [f.strip().lower() for f in args.families.split(",") if f.strip()]
    family_args = ", ".join(f'"{family}"' for family in family_list)

    cs = f"""// <auto-generated />
// Generated from feature-filename-grammar.json — do not edit. Edit the JSON and rebuild.
#nullable enable
namespace TimeWarp.Architecture.Analyzers;

using System.Collections.Generic;
using System.Collections.Immutable;

/// <summary>SSOT-backed feature filename grammar constants (TWA0015/TWA0016).</summary>
internal static class FeatureFilenameGrammar
{{
  /// <summary>Routed layers (own a layer-project Compile glob) PLUS registered-unrouted layers
  /// (e.g. "tests" — matched and validated by TWA0015/TWA0016/the membership guard, but compiled
  /// into no layer project). See feature-filename-grammar.json's "unroutedLayers".</summary>
  public static readonly ImmutableHashSet<string> Layers =
    ImmutableHashSet.Create(System.StringComparer.Ordinal, {layer_args});

  public static readonly ImmutableDictionary<string, string> FunctionToLayer =
    ImmutableDictionary.CreateRange(System.StringComparer.Ordinal, new[]
    {{
{function_entries}
    }});

  public static readonly ImmutableArray<string> FunctionsLongestFirst =
    ImmutableArray.CreateRange(new[]
    {{
{longest_first}
    }});

  /// <summary>Lowercase family directory names (e.g. "web", "api", "grpc") whose cohesive trees
  /// TWA0015/TWA0016 scope into; sourced from the Web &lt;Exec&gt; invocation's --families
  /// argument (convention-analyzers csproj) and cross-checked by the SSOT drift test.</summary>
  public static readonly ImmutableArray<string> Families =
    ImmutableArray.Create({family_args});
}}
"""
    args.out_cs.write_text(cs, encoding="utf-8")
    print(f"Generated {args.out_cs}")

  # Regex alternation is longest-first so multi-token layer names match correctly if added later.
  # Built from all_layers (routed + unrouted) so the membership guard ACCEPTS a registered-unrouted
  # suffix like "-tests" instead of reporting it as an unmatched/unrouted file.
  layer_alt = "|".join(sorted(all_layers, key=lambda layer: (-len(layer), layer)))

  args.out_props.parent.mkdir(parents=True, exist_ok=True)

  # Routed layers get Project= metadata (which layer project's Compile glob claims them).
  # Registered-unrouted layers (e.g. "tests") get an item with NO Project metadata — matched and
  # validated by the guard/analyzer, but claimed by no layer project's glob (see compile_groups,
  # which stays routed-only below).
  layer_items = "\n".join(
    f'    <FeatureFilenameGrammarLayer Include="{layer}" Project="{prefix_lower}-{layer}" />'
    for layer in layers
  )
  if unrouted_layers:
    layer_items += "\n" + "\n".join(
      f'    <FeatureFilenameGrammarLayer Include="{layer}" />'
      for layer in unrouted_layers
    )
  function_items = "\n".join(
    f'    <FeatureFilenameGrammarFunction Include="{function}" Layer="{layer}" />'
    for function, layer in sorted(functions.items())
  )
  # Hybrid Compile groups generated from the ROUTED layer list only (SSOT — do not hand-list in
  # targets). Registered-unrouted layers (e.g. "tests") deliberately get NO Compile ItemGroup here
  # — that is what keeps a co-located `-tests.cs` runfile out of every layer project's build while
  # still being matched-and-validated by the guard/analyzer above.
  # Two cohesive roots: features/ (product slices) and platform/ (host/platform clusters).
  # Both use the same -{layer} suffix → project mapping; the family's own feature-membership.targets
  # sets the roots.
  compile_groups = "\n".join(
    f"""  <ItemGroup Condition="'$(MSBuildProjectName)' == '{prefix_lower}-{layer}'">
    <Compile Include="$({prefix}FeatureTreeRoot)/**/*-{layer}.cs"
             Link="features\\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="$({prefix}PlatformTreeRoot)/**/*-{layer}.cs"
             Condition="'$({prefix}PlatformTreeRoot)' != ''"
             Link="platform\\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>"""
    for layer in layers
  )
  props = f"""<!--
  AUTO-GENERATED from source/analyzers/timewarp-architecture-convention-analyzers/feature-filename-grammar.json
  Do not edit by hand. Edit the JSON and rebuild the convention-analyzers project (or run the generator).
  Registry edit ⇒ full rebuild (analyzer incremental staleness).
  Nesting of layer suffixes is rejected at generation time (dual-match prevention).
  Hybrid includes: {prefix}FeatureTreeRoot (features/) and {prefix}PlatformTreeRoot (platform/) from
  feature-membership.targets — same -{{layer}} suffix → layer project mapping. Family: {prefix}.
-->
<Project>
  <PropertyGroup>
    <FeatureFilenameLayerSuffixRegex>-({layer_alt})$</FeatureFilenameLayerSuffixRegex>
  </PropertyGroup>
  <ItemGroup>
{layer_items}
{function_items}
  </ItemGroup>
  <!-- Hybrid includes: require tree roots set by feature-membership.targets. -->
{compile_groups}
</Project>
"""
  args.out_props.write_text(props, encoding="utf-8")
  print(f"Generated {args.out_props}")
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
