# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: timewarp.architecture
services:
    
- name: web-server
  project: ../../Source/ContainerApps/Web/Web.Server/Web.Server.csproj
  bindings:
  - port: 7000
    protocol: https

- name: grpc-server
  project: ../../Source/ContainerApps/Grpc/Grpc.Server/Grpc.Server.csproj
  bindings:
  - name: https-grpc
    port: 7227
    protocol: https
  - name: http-grpc
    port: 5290
    protocol: http

- name: api-server
  project: ../../Source/ContainerApps/Api/Api.Server/Api.Server.csproj
  bindings:
  - port: 7255
    protocol: https

- name: yarp
  project: ../../Source/ContainerApps/Yarp/Yarp.csproj
  bindings:
  - port: 8443
    protocol: https
