# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: timewarp.architecture
services:
    
- name: web-server
  project: ../../Source/ContainerApps/Web/Web.Server/Web.Server.csproj
  bindings:
  - port: 7000
    protocol: https

- name: api-server
  project: ../../Source/ContainerApps/Api/Api.Server/Api.Server.csproj
  bindings:
  - port: 7255
    protocol: https

#- name: cosmosdb
#  image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
#  bindings:
#  - port: 8081
#    name: cosmosdb-ui
#    protocol: https
#  - port: 8900
#    name: cosmosdb-8900
#  - port: 8901
#    name: cosmosdb-8901
#  - port: 8979   
#    name: cosmosdb-8979
#  - port: 10250
#    name: cosmosdb-10250
#  - port: 10251
#    name: cosmosdb-10251
#  - port: 10252
#    name: cosmosdb-10252
#  - port: 10253
#    name: cosmosdb-10253
#  - port: 10254
#    name: cosmosdb-10254
#  - port: 10350
#    name: cosmosdb-10350

#- name: rabbitmq
#  image: mcr.microsoft.com/rabbitmq/rabbitmq-server-container
