global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.Diagnostics;
global using Microsoft.CodeAnalysis.Testing;
global using Shouldly;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using TimeWarp.Architecture.Analyzers;
global using TimeWarp.Architecture.Attributes;
