// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimeWarp.Architecture.Persistence;

#nullable disable

namespace TimeWarp.Architecture.Persistence.Migrations;

[DbContext(typeof(PostgresDbContext))]
partial class PostgresDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20261010075816_AddFeedbackAttachments";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("TimeWarp.Architecture.Authorization.RolePermissionGrant", b =>
            {
                b.Property<Guid>("RoleId")
                    .HasColumnType("uuid");

                b.Property<string>("PermissionId")
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.HasKey("RoleId", "PermissionId");

                b.ToTable("role_permissions", "identity");
            });

        modelBuilder.Entity("TimeWarp.Architecture.Features.AgentLinks.Domain.AgentHumanLink", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<Guid>("AgentPrincipalId")
                    .HasColumnType("uuid");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTimeOffset?>("DecidedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("HumanPrincipalId")
                    .HasColumnType("uuid");

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.HasIndex("AgentPrincipalId", "HumanPrincipalId")
                    .IsUnique()
                    .HasFilter("\"Status\" IN (1, 2)");

                b.ToTable("agent_links", "agent_links");
            });

        modelBuilder.Entity("TimeWarp.Architecture.Features.Feedback.Domain.FeedbackAttachment", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<string>("ContentType")
                    .IsRequired()
                    .HasMaxLength(127)
                    .HasColumnType("character varying(127)");

                b.Property<Guid?>("FeedbackItemId")
                    .HasColumnType("uuid");

                b.Property<string>("FileName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<Guid>("OwnerPrincipalId")
                    .HasColumnType("uuid");

                b.Property<long>("Size")
                    .HasColumnType("bigint");

                b.Property<string>("StorageKey")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("character varying(80)");

                b.Property<DateTimeOffset>("UploadedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<long>("Version")
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.HasIndex("FeedbackItemId");

                b.HasIndex("OwnerPrincipalId");

                b.ToTable("feedback_attachments", "feedback");
            });

        modelBuilder.Entity("TimeWarp.Architecture.Features.Feedback.Domain.FeedbackItem", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<string>("Body")
                    .IsRequired()
                    .HasMaxLength(8000)
                    .HasColumnType("character varying(8000)");

                b.Property<DateTimeOffset>("FiledAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Kind")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<Guid>("OwnerPrincipalId")
                    .HasColumnType("uuid");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.HasIndex("OwnerPrincipalId");

                b.ToTable("feedback_items", "feedback");
            });

        modelBuilder.Entity("TimeWarp.Architecture.Features.PrincipalRoleAssignment", b =>
            {
                b.Property<Guid>("PrincipalId")
                    .HasColumnType("uuid");

                b.Property<Guid>("RoleId")
                    .HasColumnType("uuid");

                b.HasKey("PrincipalId", "RoleId");

                b.ToTable("principal_roles", "identity");
            });

        modelBuilder.Entity("TimeWarp.Architecture.Features.Profiles.Domain.Profile", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<string>("Email")
                    .HasMaxLength(254)
                    .HasColumnType("character varying(254)");

                b.Property<string>("Language")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<bool>("Notifications")
                    .HasColumnType("boolean");

                b.Property<string>("Region")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Theme")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.ToTable("profiles", "profiles");
            });

        modelBuilder.Entity("TimeWarp.Identity.Credential", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<string>("AccountHint")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<byte[]>("Handle")
                    .IsRequired()
                    .HasColumnType("bytea");

                b.Property<string>("Label")
                    .HasColumnType("text");

                b.Property<DateTimeOffset?>("LastUsedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Nickname")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<Guid>("PrincipalId")
                    .HasColumnType("uuid");

                b.Property<byte[]>("PublicMaterial")
                    .IsRequired()
                    .HasColumnType("bytea");

                b.Property<int>("RegisteredAttachment")
                    .HasColumnType("integer");

                b.Property<string>("RegisteredBrowser")
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<string>("RegisteredOs")
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.Property<DateTimeOffset?>("RevokedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("Type")
                    .HasColumnType("integer");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.HasIndex("PrincipalId");

                b.HasIndex("Type", "Handle")
                    .IsUnique();

                b.ToTable("credentials", "identity");
            });

        modelBuilder.Entity("TimeWarp.Identity.Principal", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("DisplayName")
                    .HasColumnType("text");

                b.Property<bool>("IsQuarantined")
                    .HasColumnType("boolean");

                b.Property<int>("Kind")
                    .HasColumnType("integer");

                b.Property<Guid?>("MergedIntoPrincipalId")
                    .HasColumnType("uuid");

                b.Property<int>("TrustTier")
                    .HasColumnType("integer");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.ToTable("principals", "identity");
            });

        modelBuilder.Entity("TimeWarp.Identity.SiteSettings", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<bool>("EntraAllowBootstrap")
                    .HasColumnType("boolean");

                b.Property<bool>("EntraSignInEnabled")
                    .HasColumnType("boolean");

                b.Property<int>("PasskeyPromptMode")
                    .HasColumnType("integer");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.ToTable("site_settings", "identity");
            });

        modelBuilder.Entity("TimeWarp.Architecture.Features.Feedback.Domain.FeedbackAttachment", b =>
            {
                b.HasOne("TimeWarp.Architecture.Features.Feedback.Domain.FeedbackItem", null)
                    .WithMany()
                    .HasForeignKey("FeedbackItemId")
                    .OnDelete(DeleteBehavior.Cascade);
            });
#pragma warning restore 612, 618
    }
}
