global using Ardalis.GuardClauses;
global using FluentValidation;
global using FluentValidation.Validators;
global using JetBrains.Annotations;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Options;
global using OneOf;
global using PhoneNumbers;
global using System.Collections.Specialized;
global using System.Net;
global using System.Net.Http;
global using System.Net.Mime;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;

// Solution usings
global using TimeWarp.Architecture.Features;
global using TimeWarp.Architecture.Types;
