$global:ApplicationNamespace = "timewarp"
$global:RegistryHost = "localhost:9443" # set to Azure Container Registry Host if you want to use the Azure Container Registry
$global:Yarp_InsecurePort=80
$global:Yarp_SecurePort=443
$global:WebServer_InsecurePort=5200
$global:WebServer_SecurePort=7200
$global:ApiServer_InsecurePort=5201
$global:GrpcServer_InsecurePort=5202
$global:AspNetCore_Environment = "Kubernetes_Docker"
