global using Ardalis.GuardClauses;
global using FluentValidation;
global using FluentValidation.Results;
global using FluentValidation.Validators;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Options;
global using OneOf;
global using PhoneNumbers;
global using System.Collections.Specialized;
global using System.Net;
global using System.Net.Http;
global using System.Net.Mime;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
// Solution usings
global using TimeWarp.Foundation.Features;
global using TimeWarp.Foundation.Types;
global using TimeWarp.Mediator;
