#region Purpose
// Contract for opening one feedback item by id.
#endregion

#region Design
// The route id is generated by [ApiRoute]. The server returns the item only to its owner.
// Another principal and a missing id are the same 404. No UserId on the query.
#endregion

namespace TimeWarp.Architecture.Features.Feedback;

[ApiEndpoint]
[EndpointAuthorize
(
  Policy = PermissionIds.FeedbackFileSelf,
  AuthenticationSchemes = AuthenticationSchemeNames.IdentitySession + "," + AuthenticationSchemeNames.MockIdentitySession
)]
public static partial class GetFeedback
{
  [ApiRoute("api/Feedback/{FeedbackItemId:guid}", HttpVerb.Get)]
  public sealed partial class Query : IApiRequest, IRequest<OneOf<Response, SharedProblemDetails>>;

  public sealed class Validator : AbstractValidator<Query>
  {
    public Validator()
    {
      RuleFor(query => query.FeedbackItemId).NotEmpty();
    }
  }

  public sealed class Response : BaseResponse
  {
    public Guid FeedbackItemId { get; }
    public string Permalink { get; }
    public FeedbackKind Kind { get; }
    public string Title { get; }
    public string Body { get; }
    public DateTimeOffset FiledAt { get; }

    public Response(
      Guid feedbackItemId,
      string permalink,
      FeedbackKind kind,
      string title,
      string body,
      DateTimeOffset filedAt)
    {
      FeedbackItemId = Guard.Against.NullOrEmpty(feedbackItemId);
      Permalink = Guard.Against.NullOrWhiteSpace(permalink);
      if (!Enum.IsDefined(kind))
      {
        throw new ArgumentException("Kind must be a defined feedback kind.", nameof(kind));
      }

      Kind = kind;
      Title = Guard.Against.NullOrWhiteSpace(title);
      Body = Guard.Against.NullOrWhiteSpace(body);
      FiledAt = filedAt;
    }
  }

  public static MockResponseFactory<Response> GetMockResponseFactory()
  {
    var feedbackItemId = Guid.Parse("11111111-1111-1111-1111-111111111111");
    return request =>
    {
      Guid id = request is Query { FeedbackItemId: var routeId } && routeId != Guid.Empty
        ? routeId
        : feedbackItemId;
      return new Response(
        id,
        $"/Feedback/{id:D}",
        FeedbackKind.Complaint,
        "Mock complaint",
        "Mock body",
        DateTimeOffset.Parse("2026-10-09T00:00:00Z"));
    };
  }
}
